version: '3.0'

services:
  
  localstack:
    image: localstack/localstack:latest
    container_name: service-sqs
    environment: 
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=sqs
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - '4566:4566'